### ISSUE TITLE
Meteor 1.2 Android

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/research-native-app-packaging#1]
Android emulation on Meteor 1.2 doesn't seem to be there yet. I followed the [updated 1.2 instructions](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac) which include bringing your own Android SDK. However, it just hangs when launching. I switched back to 1.1.0.3 for the purposes of having something that works. Maybe we can swing back around to it and see if it improves?

@jbaxleyiii

**Comment by jbaxleyiii** [comment]
@johnthepink that really really stinks. I wonder if we can find any issues related here: https://github.com/meteor/meteor/issues/4943

**Comment by johnthepink** [comment]
Vanilla Android SDK emulator tools hurray.

Looking for `emulator-x86`, but it doesn't exist. Only `emulator64-x86` does. So, I hacked it:

~~~
mv emulator64-x86 emulator-x86
~~~

This works. This scares me.
