### ISSUE TITLE
iOS Database

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/research-native-app-packaging#2]
...doesn't seem to be connecting:

![screenshot 2015-09-21 15 49 43](https://cloud.githubusercontent.com/assets/816517/10003024/65cb42ae-6078-11e5-98b8-95317d3ec340.png)

It was working

**Comment by johnthepink** [comment]
But from my phone it's good?

![img_6525](https://cloud.githubusercontent.com/assets/816517/10003165/16fff3bc-6079-11e5-83a5-5ab3a3fe2b4e.PNG)

**Comment by jbaxleyiii** [comment]
@johnthepink do you think this needs --mobile-server=localhost:3000 ?

**Comment by johnthepink** [comment]
@jbaxleyiii i tried that :/

**Comment by jbaxleyiii** [comment]
@johnthepink of course you did, because you are brilliant. hmmmmmm

**Comment by johnthepink** [comment]
@jbaxleyiii it will probably work when i get in tomorrow

**Comment by johnthepink** [comment]
works now magically
